config/routes.rb
Rails.application.routes.draw do
#reviews and distilleries
  resources :reviews
  resources :distilleries
  root to: 'distilleries#index'
#users
  resources :users, only: [ :new, :create, :destroy]
  get '/users/index'
  get '/pages/index'
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :user_verifications, :only => [:show]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
#shopping cart
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/distillery.rb
class Distillery < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_order_status
    self.order_status_id = 1 if self.order_status_id.nil?

  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
    def product_present
      if product.nil?
        errors.add(:product, "is not valid or is not active.")
      end
    end

    def order_present
      if order.nil?
        errors.add(:order, "is not a valid order.")
      end
    end

    def finalize
      self[:unit_price] = unit_price
      self[:total_price] = quantity * self[:unit_price]
    end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  def deliver_verification_instructions!
    reset_perishable_token!
    PasswordResetMailer.account_verification_instructions(self).deliver_now
  end

  def verify!
    self.verified = true
    self.save
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  validate :check_if_validated

  private

  def check_if_validated
    errors.add(:base, "You have not yet verified your account yet.") unless attempted_record && attempted_record.verified
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:index]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    #retrieve data values for use in diagrams.
    @distillery_id_raw = @review.distillery
    @distillery_details = Distillery.where(distillery: @review.distillery).pluck.flatten
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:distillery, :name, :category, :reviewpoints, :price, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    require_admin
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      @user.deliver_verification_instructions!
      redirect_to(root_path, :notice => 'You must now confirm your account. Check your email.')
    else
      render :new
    end
  end

  def destroy
    require_admin
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_index_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/distilleries_helper.rb
module DistilleriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart_row.html.erb
  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
            <div class="btn-group">
              <%= link_to "Order item(s)", order_item, { data: { confirm: "Are you sure you wish to order these item(s)?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", products_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :distillery %>
    <%= form.text_field :distillery %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :reviewpoints %>
    <%= form.number_field :reviewpoints %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

<p id="notice"><%= notice %></p>
<h1>Reviews</h1>
<br>
<div class="row pagination">
  <table id="reviews" class="table table-md table-bordered border"> <!--class="table table-md table-bordered border">-->
    <thead class="thead-light">
        <tr>
            <th class="text-center text-nowrap">Distillery</th>
            <th class="text-center text-nowrap">Name</th>
            <th class="text-center text-nowrap">Review Points</th>
            <th class="text-center text-nowrap">Price</th>
            <th>Review</th>
        </tr>
    </thead>
    <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td class="text-center text-nowrap page-item"><%= review.distillery %></td>
			      <td class="text-center text-nowrap page-item"><%= review.name %></td>
            <td class="text-center text-nowrap page-item"><%= review.reviewpoints %></td>
            <td class="text-center text-nowrap page-item"><%= review.price %><br><%= link_to 'Show', review %></td>
            <td class="page-item"><%= review.description %></td>
          </tr>
        <% end %>

    </tbody>
    </table>
</div>
<br><br><br>
<script>
$(document).ready( function () {
    $('#reviews').DataTable( {
      stateSave: true
    });

} );
</script>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>
<a href="/reviews" class="btn btn-primary" role="button">Back to reviews</a>


<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<div id="1" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>

<script>
Highcharts.chart('1', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: 'Distillery character for <%= raw @distillery_details[1] %> whisky'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                style: {
                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                }
            }
        }
    },
    series: [{
        name: 'Brands',
        colorByPoint: true,
        data: [{
            name: 'Body',
            y: <%= raw @distillery_details[2].to_i%>
        }, {
            name: 'Sweetness',
            y: <%= raw @distillery_details[3].to_i%>
        }, {
            name: 'Smokyness',
            y: <%= raw @distillery_details[4].to_i%>
        }, {
            name: 'Medicinal smokyness',
            y: <%= raw @distillery_details[5].to_i%>
        }, {
            name: 'Tobacco smokyness',
            y: <%= raw @distillery_details[6].to_i%>
        }, {
            name: 'Honey',
            y: <%= raw @distillery_details[7].to_i%>
        }, {
            name: 'Spicyness',
            y: <%= raw @distillery_details[8].to_i%>
        }, {
            name: 'Winey',
            y: <%= raw @distillery_details[9].to_i%>
        }, {
            name: 'Nutty',
            y: <%= raw @distillery_details[10].to_i%>
        }, {
            name: 'Malty',
            y: <%= raw @distillery_details[11].to_i%>
        }, {
            name: 'Fruity',
            y: <%= raw @distillery_details[12].to_i%>
        }, {
            name: 'Floral',
            y: <%= raw @distillery_details[13].to_i%>
        }]
    }]
});
</script>
<p>
  <strong>Distillery:</strong>
  <%= @review.distillery %>
</p>

<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @review.category %>
</p>

<p>
  <strong>Reviewpoints:</strong>
  <%= @review.reviewpoints %>
</p>

<p>
  <strong>Price:</strong>
  <%= @review.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>