config/routes.rb
Rails.application.routes.draw do
#reviews and distilleries
  resources :reviews
  resources :distilleries
  root to: 'distilleries#index'
#users
  resources :users, only: [ :new, :create, :destroy]
  get '/users/index'
  get '/pages/index'
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :user_verifications, :only => [:show]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
#shopping cart
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/distillery.rb
class Distillery < ApplicationRecord
end

app/controllers/distilleries_controller.rb
class DistilleriesController < ApplicationController
  before_action :set_distillery, only: [:show, :edit, :update, :destroy]
  # GET /distilleries
  # GET /distilleries.json
  def index
    @distilleries = Distillery.all


  end

  # GET /distilleries/1
  # GET /distilleries/1.json
  def show
    #retrieve reviews on whiskies of the respective distillery
    @distillery_name = @distillery.distillery
    @distillery_reviews = Review.where(distillery: @distillery.distillery).pluck
  end

  # GET /distilleries/new
  def new
    @distillery = Distillery.new
  end

  # GET /distilleries/1/edit
  def edit
  end

  # POST /distilleries
  # POST /distilleries.json
  def create
    @distillery = Distillery.new(distillery_params)

    respond_to do |format|
      if @distillery.save
        format.html { redirect_to @distillery, notice: 'Distillery was successfully created.' }
        format.json { render :show, status: :created, location: @distillery }
      else
        format.html { render :new }
        format.json { render json: @distillery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /distilleries/1
  # PATCH/PUT /distilleries/1.json
  def update
    respond_to do |format|
      if @distillery.update(distillery_params)
        format.html { redirect_to @distillery, notice: 'Distillery was successfully updated.' }
        format.json { render :show, status: :ok, location: @distillery }
      else
        format.html { render :edit }
        format.json { render json: @distillery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /distilleries/1
  # DELETE /distilleries/1.json
  def destroy
    @distillery.destroy
    respond_to do |format|
      format.html { redirect_to distilleries_url, notice: 'Distillery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_distillery
      @distillery = Distillery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def distillery_params
      params.require(:distillery).permit(:distillery, :body, :sweetness, :smoky, :medicinal, :tobacco, :honey, :spicy, :winey, :nutty, :malty, :fruity, :floral, :postcode, :latitude, :longtitude )
    end
end

app/helpers/distilleries_helper.rb
module DistilleriesHelper
end

app/views/distilleries/_form.html.erb
<%= form_with(model: distillery, local: true) do |form| %>
  <% if distillery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(distillery.errors.count, "error") %> prohibited this distillery from being saved:</h2>

      <ul>
      <% distillery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :distillery %>
    <%= form.text_field :distillery %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.number_field :body %>
  </div>

  <div class="field">
    <%= form.label :sweetness %>
    <%= form.number_field :sweetness %>
  </div>

  <div class="field">
    <%= form.label :smoky %>
    <%= form.number_field :smoky %>
  </div>

  <div class="field">
    <%= form.label :medicinal %>
    <%= form.number_field :medicinal %>
  </div>

  <div class="field">
    <%= form.label :tobacco %>
    <%= form.number_field :tobacco %>
  </div>

  <div class="field">
    <%= form.label :honey %>
    <%= form.number_field :honey %>
  </div>

  <div class="field">
    <%= form.label :spicy %>
    <%= form.number_field :spicy %>
  </div>

  <div class="field">
    <%= form.label :winey %>
    <%= form.number_field :winey %>
  </div>

  <div class="field">
    <%= form.label :nutty %>
    <%= form.number_field :nutty %>
  </div>

  <div class="field">
    <%= form.label :malty %>
    <%= form.number_field :malty %>
  </div>

  <div class="field">
    <%= form.label :fruity %>
    <%= form.number_field :fruity %>
  </div>

  <div class="field">
    <%= form.label :floral %>
    <%= form.number_field :floral %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.number_field :postcode %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.number_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longtitude %>
    <%= form.number_field :longtitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/distilleries/edit.html.erb
<h1>Editing Distillery</h1>

<%= render 'form', distillery: @distillery %>

<%= link_to 'Show', @distillery %> |
<%= link_to 'Back', distilleries_path %>

app/views/distilleries/index.html.erb
<p id="notice"><%= notice %></p>
<style>
  html, body {
  height: 100%;
  margin: 0;
  padding: 0;
  }
  #map { height: 70%; width: 100%; margin: 0; padding: 0; overflow: hidden; }
 </style>
</head>
  <body><br>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md">
        <div id="map" ></div>
      </div>
              <div class="col-md" style="font-size: 20px;">Welcome to Whiskyinfo! Select a distillery on the map to the left and click the distillery name in the pop-up. You will be redirected to a page giving detailed information about each distillery's taste character and reviews and price information about whiskies this distillery produces. Have fun exploring the site! To add a new distillery, click here: <%= link_to 'New Distillery', new_distillery_path %>
</div>
      </div>
    <script>

      function initMap() {
          map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 57, lng: -5},
          zoom: 6,

        });

        var mapStyle = [{
            'featureType': 'all',
            'elementType': 'all',
            'stylers': [{'visibility': 'off'}]
          }, {
            'featureType': 'landscape',
            'elementType': 'geometry',
            'stylers': [{'visibility': 'on'}, {'color': '#fcfcfc'}]
          }, {
            'featureType': 'water',
            'elementType': 'labels',
            'stylers': [{'visibility': 'off'}]
          }, {
            'featureType': 'water',
            'elementType': 'geometry',
            'stylers': [{'visibility': 'on'}, {'hue': '#5f94ff'}, {'lightness': 60}]
          }];


        <% @distilleries.each do |s| %>
        var marker = new google.maps.Marker({
        position: {lat: <%= s.latitude %>, lng: <%= s.longtitude %>},
        map: map,
        icon: {
        url: "/pointer.png",
  		  scaledSize: new google.maps.Size(35, 45),
        animation:google.maps.Animation.DROP
      }
      }).addListener('click', function(){
          new google.maps.InfoWindow({
          content: '<div id="content">'+
          '<div id="siteNotice">'+
          '</div>'+
          '<h5>' + '<%= link_to s.distillery, "distilleries/#{s.id}}" %>' +'</h5>'+
          '</div>'
              }).open(map, this);
      });

      <% end %>
    }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXw9tFp-fQLKJtwb4F3-BVDx4XQZbj8vk&callback=initMap">
    </script>

app/views/distilleries/new.html.erb
<h1>New Distillery information</h1>

<%= render 'form', distillery: @distillery %>

<%= link_to 'Back', distilleries_path %>

app/views/distilleries/show.html.erb
<p id="notice"><%= notice %></p><br>
<h3><%= @distillery.distillery%> distillery facts</h3>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<div id="2" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>

<script>
Highcharts.chart('2', {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: '<%= @distillery.distillery %> distillery character'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                style: {
                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                }
            }
        }
    },
    series: [{
        name: 'Brands',
        colorByPoint: true,
        data: [{
            name: 'Body',
            y: <%= @distillery.body.to_i%>
        }, {
            name: 'Sweetness',
            y: <%= @distillery.sweetness.to_i%>
        }, {
            name: 'Smokyness',
            y: <%= @distillery.smoky.to_i%>
        }, {
            name: 'Medicinal smokyness',
            y: <%= @distillery.medicinal.to_i%>
        }, {
            name: 'Tobacco smokyness',
            y: <%= @distillery.tobacco.to_i%>
        }, {
            name: 'Honey',
            y: <%= @distillery.honey.to_i%>
        }, {
            name: 'Spicyness',
            y: <%= @distillery.spicy.to_i%>
        }, {
            name: 'Winey',
            y: <%= @distillery.winey.to_i%>
        }, {
            name: 'Nutty',
            y: <%= @distillery.nutty.to_i%>
        }, {
            name: 'Malty',
            y: <%= @distillery.malty.to_i%>
        }, {
            name: 'Fruity',
            y: <%= @distillery.fruity.to_i%>
        }, {
            name: 'Floral',
            y: <%= @distillery.floral.to_i%>
        }]
    }]
});
</script>
<p>
  <strong>Postcode:</strong>
  <%= @distillery.postcode %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @distillery.latitude %>
</p>

<p>
  <strong>Longtitude:</strong>
  <%= @distillery.longtitude %>
</p>
<br>
<h3><%= @distillery.distillery%> whiskies:</h3>
<div class="row">
<% @distillery_reviews.each do |s| %>
  <div class="col-sm-4">
      <div class="card box-shadow">
          <div class="card-body">
            <h5 class="card-title"> <%= s[2]%> </h5>
            <p class="card-text"><b>Category:</b> <%= s[3]%><br>
              <b>Price:</b> <%= s[5] %> USD<br>
              <b>Review points:</b> <%= s[4] %><br>
              <b>Review:</b> <%= s[6] %><br>
          </div>
          <div class="card-footer">
            <small class="text-muted">Distillery: <%= s[1] %></small>
          </div>
      </div>
    </div>
<% end %>
</div><br>