config/routes.rb
Rails.application.routes.draw do
#reviews and distilleries
  resources :reviews
  resources :distilleries
  root to: 'distilleries#index'
#users
  resources :users, only: [ :new, :create, :destroy]
  get '/users/index'
  get '/pages/index'
  resources :user_sessions, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :user_verifications, :only => [:show]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
#shopping cart
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/distillery.rb
class Distillery < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  before_validation :set_order_status
  belongs_to :order_status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_order_status
    self.order_status_id = 1 if self.order_status_id.nil?

  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private
    def product_present
      if product.nil?
        errors.add(:product, "is not valid or is not active.")
      end
    end

    def order_present
      if order.nil?
        errors.add(:order, "is not a valid order.")
      end
    end

    def finalize
      self[:unit_price] = unit_price
      self[:total_price] = quantity * self[:unit_price]
    end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end

  def deliver_verification_instructions!
    reset_perishable_token!
    PasswordResetMailer.account_verification_instructions(self).deliver_now
  end

  def verify!
    self.verified = true
    self.save
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  validate :check_if_validated

  private

  def check_if_validated
    errors.add(:base, "You have not yet verified your account yet.") unless attempted_record && attempted_record.verified
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    require_admin
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      @user.deliver_verification_instructions!
      redirect_to(root_path, :notice => 'You must now confirm your account. Check your email.')
    else
      render :new
    end
  end

  def destroy
    require_admin
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_index_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/distilleries_helper.rb
module DistilleriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link cart-text" %>

app/views/layouts/_navigation.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script scr="//netdna.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Whiskyinfo', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/reviews/">Whisky Reviews</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">Distillery Map</a>
      </li>
      <% if current_user %>
          <li class="nav-item"><a class="nav-link"<%= link_to 'Products', products_path %></a></li>
          <li class ="nav-item"><a class="nav-link" href="/pages/index"><b>Logged in as: <%= current_user.email %></b></a></li>
          <li class ="nav-item"><a class="nav-link"<%= link_to 'Sign Out', sign_out_path, method: :delete %></a></li>
          <% if current_user.email == "admin@admin.admin"%>
              <li class="nav-item">
                  <a class="nav-link" href="/users/index">Admin Dashboard</a>
                  </li>
          <% end %>
      <% else %>
          <li class ="nav-item"><a class="nav-link"<%= link_to 'Sign In', sign_in_path %></a></li>
          <li class ="nav-item"><a class="nav-link" href="/pages/index">Sign Up</a></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
    <title>Whiskyinfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% if current_user %>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    <% end %>
    <%= yield %>
  </body>
  <div class="footer">
  <p>Created by Jakob Fischer 2018</p>
</div>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="container">
    <% if current_user %>
      <div class="page-header"><h1>Welcome back!</h1></div>

      <h2>Some info about you...</h2>

      <div class="well well-lg">
        <ul>
          <li>Login count: <%= current_user.login_count %></li>
          <li>Failed login count: <%= current_user.failed_login_count %></li>
          <li>Last request: <%= current_user.last_request_at %></li>
          <li>Current login at: <%= current_user.current_login_at %></li>
          <li>Last login at: <%= current_user.last_login_at %></li>
          <li>Current login IP: <%= current_user.current_login_ip %></li>
          <li>Last login IP: <%= current_user.last_login_ip %></li>
        </ul>
      </div>
    <% else %>
      <h1>Welcome!</h1>
      <p>Sign up to get started.</p>
      <p>
        <%= link_to new_user_path, class: 'btn btn-primary btn-lg' do %>
          Sign Up &raquo;
        <% end %>
      </p>
    <% end %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>